# Generated by Django 2.2.7 on 2019-12-03 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodstype',
            name='logo',
            field=models.CharField(default='', max_length=20, verbose_name='标识'),
            preserve_default=False,
        ),
    ]
