# Generated by Django 2.2.7 on 2019-12-04 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_goodstype_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodstype',
            name='logo',
            field=models.CharField(max_length=50, verbose_name='标识'),
        ),
    ]
